baseURL: https://staticvish.github.io/
languageCode: en-us
title: Site of Visveswaran Vaidyanathan a.k.a StaticVish
theme: custom
canonifyURLs: true
enableGitInfo: true
params:
  author: Visveswaran Vaidyanathan
  description: StaticVish's Awesome Site
  brand: StaticVish's Awesome Site
  