# baseURL = "https://staticvish.github.io/"
baseURL = "/"
languageCode = "en-us"
title = "Site of Visveswaran Vaidyanathan a.k.a StaticVish"
theme = "custom"
canonifyURLs = "true"

[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Content-Security-Policy = 'script-src localhost:1313'
    Referrer-Policy = 'strict-origin-when-cross-origin'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'